name = "apubhook"
compatibility_date = "2023-01-01"
main = "src/index.ts"

[site]
bucket = "./public"

[[ d1_databases ]]
binding = "DB"
database_name = "apubhook"
database_id = ""

[vars]
PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----
"""